// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200308141839_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Domain.Ville", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<Guid?>("ProvinceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("Domain.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addresse")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("Telephone")
                        .HasMaxLength(25);

                    b.Property<Guid?>("VilleId");

                    b.Property<string>("ZoneCode")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("VilleId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Domain.Ville", b =>
                {
                    b.HasOne("Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("Domain.Zone", b =>
                {
                    b.HasOne("Domain.Ville", "Ville")
                        .WithMany()
                        .HasForeignKey("VilleId");
                });
#pragma warning restore 612, 618
        }
    }
}
